arm_joint_1:
has_velocity_limits: true
max_velocity: 1.0
has_acceleration_limits: true
max_acceleration: 1.0
has_position_limits: true
min_position: -3.1416
max_position: 3.1416


arm_joint_2:
has_velocity_limits: true
max_velocity: 1.0
has_acceleration_limits: true
max_acceleration: 1.0
has_position_limits: true
min_position: -1.5708
max_position: 1.5708


arm_joint_3:
has_velocity_limits: true
max_velocity: 1.0
has_acceleration_limits: true
max_acceleration: 1.0
has_position_limits: true
min_position: -2.0
max_position: 2.0


arm_joint_4:
has_velocity_limits: true
max_velocity: 1.0
has_acceleration_limits: true
max_acceleration: 1.0
has_position_limits: true
min_position: -1.5708
max_position: 1.5708


arm_joint_5:
has_velocity_limits: false
has_acceleration_limits: false
has_position_limits: false